sonar.organization=rodcordeiro
sonar.projectKey=rodcordeiro_banky
sonar.sources=.
sonar.coverage.exclusions=src/modules/nlp/classifiers/samples/*.json
sonar.cpd.exclusions=src/modules/nlp/classifiers/samples/*.json
